name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [master]  # 如果你的默认分支是 master，就保持 master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build complete
        run: echo "Page build done."
